# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'SwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for SwiftDemo
  
  pod 'Alamofire', '5.10.1'
  pod 'SnapKit'
  pod 'Toast-Swift', '~> 5.1.1'
  
  # Please keep one line from the following lines:
    pod 'SwifterSwift', '6.2.0'               # All Extensions
    pod 'SwifterSwift/SwiftStdlib'   # Standard Library Extensions
    pod 'SwifterSwift/Foundation'    # Foundation Extensions
    pod 'SwifterSwift/UIKit'         # UIKit Extensions
#    pod 'SwifterSwift/Cocoa'         # Cocoa Extensions
#    pod 'SwifterSwift/Dispatch'       # Dispatch Extensions

  target 'SwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftDemoUITests' do
    # Pods for testing
  end

end
